import * as React from 'react';
declare class JqxGantt extends React.PureComponent<IGanttProps, IState> {
    protected static getDerivedStateFromProps(props: IGanttProps, state: IState): null | IState;
    private _jqx;
    private _id;
    private _componentSelector;
    constructor(props: IGanttProps);
    componentDidMount(): void;
    componentDidUpdate(): void;
    componentWillUnmount(): void;
    render(): React.ReactNode;
    setOptions(options: IGanttProps): void;
    getOptions(option: string): any;
    addFilter(columns: object | object[], filterGroup: object): void;
    clearFilters(): void;
    clearSort(): void;
    clearSelection(): void;
    clearState(): void;
    clearTasks(): void;
    clearResources(): void;
    createConnection(startTaskIndex: number | string, taskEndIndex?: number | string, connectionType?: number, lag?: number): void;
    collapse(id: string | number): void;
    beginUpdate(): void;
    endUpdate(): void;
    ensureVisible(taskId: string | number): void;
    expand(id: string | number): void;
    exportData(dataFormat: string, callback?: Function): void;
    getConnections(): any[];
    getConnectionDetails(connectionId: string): object | undefined;
    getState(): [];
    getItemPath(item: object): string;
    getTask(itemId: string | number): object;
    getTasks(): [];
    getTaskIndex(task: object): number;
    getTaskConnections(taskId: string | number | object): any;
    getTaskProject(task: object): object | undefined;
    getResource(itemId: string | number): object;
    getResources(): [];
    getResourceIndex(resource: object): number;
    getResourceTasks(resource: object | string | number): any[];
    getSelectedIds(): any[] | null;
    getSelectedTasks(): any[] | null;
    getSelectedResources(): any[] | null;
    getWorkingHours(): any[];
    hideTooltip(): any[];
    isWorkingDay(date: Date): void;
    loadState(state?: []): void;
    removeAllConnections(): void;
    removeConnection(startTaskIndex: number | string, taskEndIndex?: number, connectionType?: number): object;
    removeTaskConnection(taskStart: number | string | object, taskEnd?: number | string | object): void;
    showTooltip(target: HTMLElement, content?: string): void;
    saveState(state?: []): void;
    insertTask(taskObject: object, project?: string | number | object, index?: number): string | number | undefined;
    updateTask(taskId: string | number | object, taskObject: object): void;
    removeTask(taskId: string | number | object): void;
    insertResource(resourceId: string | number, resourceObject?: object): void;
    updateResource(resourceId: string | number | object, taskObject: object): void;
    removeResource(resourceId: string | number | object): void;
    openWindow(taskId: string | number | object): void;
    closeWindow(): void;
    print(): void;
    setWorkTime(settings: {
        days: (number | string | number[])[];
        hours: (number | string | number[])[];
    }): void;
    selectTask(id: string | number): void;
    selectResource(id: string | number): void;
    unselectTask(id: string | number): void;
    unselectResource(id: string | number): void;
    unsetWorkTime(settings: {
        days: (number | string | number[])[];
        hours: (number | string | number[])[];
    }): void;
    sort(columns: any[] | undefined): void;
    private _manageProps;
    private _wireEvents;
}
export default JqxGantt;
export declare const jqx: any;
export declare const JQXLite: any;
interface IState {
    lastProps: object;
}
interface IGanttOptions {
    adjustToNonworkingTime?: boolean;
    autoSchedule?: boolean;
    autoScheduleStrictMode?: boolean;
    autoScrollStep?: number;
    columnMenu?: boolean;
    columnMinWidth?: string | number;
    columnResize?: boolean;
    columnResizeFeedback?: boolean;
    currentTime?: string | Date;
    currentTimeIndicator?: boolean;
    currentTimeIndicatorInterval?: number;
    dataExportFileName?: string;
    source?: any;
    dayFormat?: string;
    dateEnd?: string | Date;
    dateStart?: string | Date;
    dateMarkers?: {
        label?: string;
        date: Date | string;
        className?: string;
    }[];
    disabled?: boolean;
    disableAutoScroll?: boolean;
    disableTaskDrag?: boolean;
    disableTaskProgressChange?: boolean;
    disableTaskResize?: boolean;
    disableSelection?: boolean;
    disableSegmentDrag?: boolean;
    disableSegmentResize?: boolean;
    disableWindowEditor?: boolean;
    durationUnit?: string;
    filterRow?: boolean;
    firstDayOfWeek?: number;
    groupByResources?: boolean;
    headerTemplate?: any;
    hideDateMarkers?: boolean;
    hideTimelineHeader?: boolean;
    hideTimelineHeaderDetails?: boolean;
    hideTimelineSecondHeaderDetails?: boolean;
    hideResourcePanel?: boolean;
    horizontalScrollBarVisibility?: string;
    hourFormat?: string;
    infiniteTimeline?: boolean;
    infiniteTimelineStep?: number;
    inverted?: boolean;
    keyboardNavigation?: boolean;
    max?: string | Date;
    min?: string | Date;
    monthFormat?: string;
    monthScale?: string;
    nonworkingDays?: number[];
    nonworkingHours?: number[] | number[][];
    onTaskRender?: any;
    popupWindowCustomizationFunction?: any;
    popupWindowTabs?: string[];
    progressLabelFormatFunction?: any;
    quarterFormat?: string;
    resources?: {
        label: string;
        capacity: number;
        value: string;
        workload: number;
        progress: number;
        id: string;
        class: string;
    }[];
    resourceColumns?: {
        label: string;
        value: string;
    }[];
    resourceFiltering?: boolean;
    resourceGroupFormatFunction?: any;
    resourcePanelHeaderTemplate?: any;
    resourcePanelMin?: number | string;
    resourcePanelSize?: number | string;
    resourcePanelRefreshRate?: number;
    resourceTimelineFormatFunction?: any;
    resourceTimelineMode?: string;
    resourceTimelineView?: string;
    rightToLeft?: boolean;
    selectedTaskIds?: number[] | string[];
    selectedResourceIds?: number[] | string[];
    shadeUntilCurrentTime?: boolean;
    showSelectionColumn?: boolean;
    showBaseline?: boolean;
    showProgressLabel?: boolean;
    snapToNearest?: boolean;
    sortFunction?: {
        (dataSource: any, sortColumns: string[], directions: string[], defaultCompareFunctions: {
            (firstRecord: any, secondRecord: any): number;
        }[]): void;
    };
    sortMode?: string;
    tasks?: {
        label: string;
        dateStart: string | Date;
        dateEnd: string | Date;
        expanded?: boolean;
        progress?: number;
        type?: string;
    }[];
    taskColumns?: {
        label: string;
        value: string;
    }[];
    taskFiltering?: boolean;
    taskPanelMin?: string | number;
    taskPanelSize?: string | number;
    timelineMin?: string | number;
    treeMin?: string | number;
    treeSize?: string | number;
    timelineHeaderFormatFunction?: any;
    tooltip?: object;
    verticalScrollBarVisibility?: string;
    view?: string;
    yearFormat?: string;
    weekFormat?: string;
    theme?: string;
}
export interface IGanttProps extends IGanttOptions {
    className?: string;
    style?: React.CSSProperties;
    onBeginUpdate?: (e?: Event) => void;
    onEndUpdate?: (e?: Event) => void;
    onConnectionStart?: (e?: Event) => void;
    onConnectionEnd?: (e?: Event) => void;
    onChange?: (e?: Event) => void;
    onColumnResize?: (e?: Event) => void;
    onClosing?: (e?: Event) => void;
    onClose?: (e?: Event) => void;
    onCollapse?: (e?: Event) => void;
    onDragStart?: (e?: Event) => void;
    onDragEnd?: (e?: Event) => void;
    onExpand?: (e?: Event) => void;
    onFilter?: (e?: Event) => void;
    onItemClick?: (e?: Event) => void;
    onItemInsert?: (e?: Event) => void;
    onItemRemove?: (e?: Event) => void;
    onItemUpdate?: (e?: Event) => void;
    onOpening?: (e?: Event) => void;
    onOpen?: (e?: Event) => void;
    onProgressChangeStart?: (e?: Event) => void;
    onProgressChangeEnd?: (e?: Event) => void;
    onResizeStart?: (e?: Event) => void;
    onResizeEnd?: (e?: Event) => void;
    onSort?: (e?: Event) => void;
    onScrollBottomReached?: (e?: Event) => void;
    onScrollTopReached?: (e?: Event) => void;
    onScrollLeftReached?: (e?: Event) => void;
    onScrollRightReached?: (e?: Event) => void;
}
